[package]
name = "wiringpi-repro-case"
version = "0.1.0"
authors = ["Neil McAlister <neil.mcalister@futurice.com>"]

[dependencies]
wiringpi = {git = "https://github.com/yuhe00/rust-wiringpi/", branch = "fix-build" }